//! End-to-end execution of selected LDBC SNB Interactive Complex queries.
//!
//! The fixture seeds a hand-crafted miniature SNB graph (6 Persons, 8
//! Messages, 4 Comments, KNOWS / HAS_CREATOR / LIKES / REPLY_OF edges)
//! and runs IC2 / IC7 / IC8 / IC9 end-to-end. Each test parses the
//! canonical .cypher fixture, lowers it, executes against `Snapshot`
//! and asserts on the produced rows.
//!
//! Notes:
//! - `creationDate` properties are stored as i64 epoch-millis to keep
//! the comparison surface trivial; the query parameter `$maxDate` is
//! passed as `RuntimeValue::Integer`.
//! - Node IDs are UUIDv7 generated by `NodeId::new()`; queries reference
//! them via `$personId` as a string parameter.
//! - We do NOT call `WriterSession::flush` — all property data stays in
//! the memtable, where v1 reads return the full property map for both
//! nodes and edges.

use std::collections::BTreeMap;
use std::sync::Arc;

use namidb_core::id::{NamespaceId, NodeId};
use namidb_core::value::Value as CoreValue;
use namidb_storage::{EdgeWriteRecord, NamespacePaths, NodeWriteRecord, WriterSession};
use object_store::memory::InMemory;
use object_store::ObjectStore;

use namidb_query::{execute, lower, parse, Params, RuntimeValue};

fn store() -> Arc<dyn ObjectStore> {
    Arc::new(InMemory::new())
}

fn paths(name: &str) -> NamespacePaths {
    NamespacePaths::new("tenants", NamespaceId::new(name).unwrap())
}

fn read_fixture(name: &str) -> String {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {}", path, e))
}

// ──────────────────────────────────────────────────────────────────────
// Mini SNB graph
// ──────────────────────────────────────────────────────────────────────

struct SnbFixture {
    alice: NodeId,
    bob: NodeId,
    carol: NodeId,
    dave: NodeId,
    eve: NodeId,
    frank: NodeId,
    msg_ids: Vec<NodeId>,
    comment_ids: Vec<NodeId>,
    /// First message creator order: msg[0] by Alice, msg[1] by Bob, etc.
    msg_creators: Vec<NodeId>,
    /// Comment creators: comment[0] by Bob, comment[1] by Carol, etc.
    comment_creators: Vec<NodeId>,
    /// Comment[i] replies to msg[reply_targets[i]]; -1 if replies to another comment.
    comment_replies_to_msg: Vec<i32>,
}

fn person(first: &str, last: &str, age: i32) -> NodeWriteRecord {
    let mut p: BTreeMap<String, CoreValue> = BTreeMap::new();
    p.insert("firstName".into(), CoreValue::Str(first.into()));
    p.insert("lastName".into(), CoreValue::Str(last.into()));
    p.insert("age".into(), CoreValue::I64(age as i64));
    NodeWriteRecord {
        properties: p,
        schema_version: 1,
    }
}

fn message(content: &str, creation_date: i64) -> NodeWriteRecord {
    let mut p = BTreeMap::new();
    p.insert("content".into(), CoreValue::Str(content.into()));
    p.insert("creationDate".into(), CoreValue::I64(creation_date));
    NodeWriteRecord {
        properties: p,
        schema_version: 1,
    }
}

fn comment(content: &str, creation_date: i64) -> NodeWriteRecord {
    let mut p = BTreeMap::new();
    p.insert("content".into(), CoreValue::Str(content.into()));
    p.insert("creationDate".into(), CoreValue::I64(creation_date));
    NodeWriteRecord {
        properties: p,
        schema_version: 1,
    }
}

fn bare_edge() -> EdgeWriteRecord {
    EdgeWriteRecord {
        properties: BTreeMap::new(),
        schema_version: 1,
    }
}

fn likes_edge(creation_date: i64) -> EdgeWriteRecord {
    let mut p = BTreeMap::new();
    p.insert("creationDate".into(), CoreValue::I64(creation_date));
    EdgeWriteRecord {
        properties: p,
        schema_version: 1,
    }
}

async fn build_snb_micro_graph(writer: &mut WriterSession) -> SnbFixture {
    let alice = NodeId::new();
    let bob = NodeId::new();
    let carol = NodeId::new();
    let dave = NodeId::new();
    let eve = NodeId::new();
    let frank = NodeId::new();

    writer
        .upsert_node("Person", alice, &person("Alice", "Anderson", 30))
        .unwrap();
    writer
        .upsert_node("Person", bob, &person("Bob", "Brown", 25))
        .unwrap();
    writer
        .upsert_node("Person", carol, &person("Carol", "Clark", 35))
        .unwrap();
    writer
        .upsert_node("Person", dave, &person("Dave", "Davies", 28))
        .unwrap();
    writer
        .upsert_node("Person", eve, &person("Eve", "Edwards", 40))
        .unwrap();
    writer
        .upsert_node("Person", frank, &person("Frank", "Foley", 33))
        .unwrap();

    // KNOWS edges (directed; queries that use `-[:KNOWS]-` traverse both
    // directions). Insert one direction; bidirectional traversal uses
    // RelationshipDirection::Both at the executor level.
    let knows_pairs = [
        (alice, bob),
        (alice, carol),
        (bob, dave),
        (carol, eve),
        (dave, frank),
        (eve, frank),
    ];
    for (src, dst) in knows_pairs {
        writer.upsert_edge("KNOWS", src, dst, &bare_edge()).unwrap();
    }

    // 8 Messages, ordered by creationDate. Creators rotate through
    // friends/non-friends of Alice so IC2/IC9 produce distinguishable
    // result sets.
    let base = 1_700_000_000_000_i64;
    let day = 86_400_000_i64;
    let msg_contents = [
        "Hello world",
        "Cypher rocks",
        "Property graphs",
        "Coffee time",
        "Late-night thoughts",
        "Friday vibes",
        "Holiday plans",
        "Year-end recap",
    ];
    let msg_dates = [
        base,
        base + day,
        base + 2 * day,
        base + 3 * day,
        base + 4 * day,
        base + 5 * day,
        base + 6 * day,
        base + 7 * day,
    ];
    // Creators: msg0 by Bob, msg1 by Carol, msg2 by Dave, msg3 by Eve,
    //           msg4 by Frank, msg5 by Bob, msg6 by Carol, msg7 by Eve.
    // Alice's friends in this graph (KNOWS undirected): Bob, Carol.
    // Friends-of-friends from Alice: Dave (via Bob), Eve (via Carol).
    let msg_creators = vec![bob, carol, dave, eve, frank, bob, carol, eve];
    let mut msg_ids = Vec::with_capacity(8);
    for (i, content) in msg_contents.iter().enumerate() {
        let id = NodeId::new();
        msg_ids.push(id);
        writer
            .upsert_node("Message", id, &message(content, msg_dates[i]))
            .unwrap();
        writer
            .upsert_edge("HAS_CREATOR", id, msg_creators[i], &bare_edge())
            .unwrap();
    }

    // LIKES edges with `creationDate` property on the edge. Choose
    // dates such that we have meaningful (latest like, message ID)
    // tuples per liker.
    // Liker Dave likes msg0 (at base+10*day) and msg2 (at base+11*day).
    // Liker Eve likes msg0 (at base+9*day).
    // Liker Frank likes msg5 (at base+12*day).
    let likes = [
        (dave, msg_ids[0], base + 10 * day),
        (dave, msg_ids[2], base + 11 * day),
        (eve, msg_ids[0], base + 9 * day),
        (frank, msg_ids[5], base + 12 * day),
    ];
    for (src, dst, ts) in likes {
        writer
            .upsert_edge("LIKES", src, dst, &likes_edge(ts))
            .unwrap();
    }

    // 4 Comments. comment0 replies to msg0, comment1 replies to msg0
    // (same target → IC8 should still distinguish them), comment2
    // replies to msg5, comment3 replies to msg0. All by friends of
    // Alice or her friends-of-friends.
    let comment_contents = ["Nice!", "Agreed", "Going!", "+1"];
    let comment_dates = [
        base + 13 * day,
        base + 14 * day,
        base + 15 * day,
        base + 16 * day,
    ];
    let comment_creators = vec![carol, dave, eve, frank];
    let comment_replies_to_msg = vec![0i32, 0, 5, 0];
    let mut comment_ids = Vec::with_capacity(4);
    for (i, content) in comment_contents.iter().enumerate() {
        let id = NodeId::new();
        comment_ids.push(id);
        writer
            .upsert_node("Comment", id, &comment(content, comment_dates[i]))
            .unwrap();
        writer
            .upsert_edge("HAS_CREATOR", id, comment_creators[i], &bare_edge())
            .unwrap();
        let target_msg = msg_ids[comment_replies_to_msg[i] as usize];
        writer
            .upsert_edge("REPLY_OF", id, target_msg, &bare_edge())
            .unwrap();
    }

    writer.commit_batch().await.unwrap();

    SnbFixture {
        alice,
        bob,
        carol,
        dave,
        eve,
        frank,
        msg_ids,
        comment_ids,
        msg_creators,
        comment_creators,
        comment_replies_to_msg,
    }
}

// ──────────────────────────────────────────────────────────────────────
// IC2 — Recent messages by friends
// ──────────────────────────────────────────────────────────────────────

#[tokio::test]
async fn ic02_recent_messages_by_friends() {
    let mut writer = WriterSession::open(store(), paths("ic02")).await.unwrap();
    let f = build_snb_micro_graph(&mut writer).await;
    let snapshot = writer.snapshot();

    let src = read_fixture("ic02_recent_messages_by_friends.cypher");
    let q = parse(&src).expect("parse IC2");
    let plan = lower(&q).expect("lower IC2");

    let mut params = Params::new();
    params.insert("personId".into(), RuntimeValue::String(f.alice.to_string()));
    // Pick a maxDate that includes all messages.
    let max_date = 1_700_000_000_000_i64 + 100 * 86_400_000;
    params.insert("maxDate".into(), RuntimeValue::Integer(max_date));

    let rows = execute(&plan, &snapshot, &params).await.expect("exec IC2");

    // Alice's KNOWS friends (undirected): Bob (alice→bob) and Carol
    // (alice→carol). Messages by Bob (msg0, msg5) and Carol (msg1, msg6).
    // 4 messages total, ordered by creationDate DESC then messageId ASC.
    let names: Vec<String> = rows
        .iter()
        .map(|r| match r.get("personFirstName") {
            Some(RuntimeValue::String(s)) => s.clone(),
            other => panic!("unexpected: {:?}", other),
        })
        .collect();
    assert_eq!(rows.len(), 4, "expected 4 messages, got {:?}", names);
    // Most recent first: msg6 (Carol, day 6), msg5 (Bob, day 5),
    // msg1 (Carol, day 1), msg0 (Bob, day 0).
    let expected_authors = vec!["Carol", "Bob", "Carol", "Bob"];
    assert_eq!(names, expected_authors);

    // Each row's personId should be the friend's NodeId as string.
    for row in &rows {
        match row.get("personId") {
            Some(RuntimeValue::String(s)) => {
                assert!(s == &f.bob.to_string() || s == &f.carol.to_string());
            }
            other => panic!("unexpected: {:?}", other),
        }
    }
}

// ──────────────────────────────────────────────────────────────────────
// IC7 — Recent likers (head(collect(...)) aggregate-nesting smoke)
// ──────────────────────────────────────────────────────────────────────

#[tokio::test]
async fn ic07_recent_likers() {
    let mut writer = WriterSession::open(store(), paths("ic07")).await.unwrap();
    let f = build_snb_micro_graph(&mut writer).await;
    let snapshot = writer.snapshot();

    let src = read_fixture("ic07_recent_likers.cypher");
    let q = parse(&src).expect("parse IC7");
    let plan = lower(&q).expect("lower IC7");

    let mut params = Params::new();
    // Bob authored msg0 and msg5 → likers are Dave (msg0), Eve (msg0),
    // Frank (msg5). Each appears once because IC7 groups by liker.
    params.insert("personId".into(), RuntimeValue::String(f.bob.to_string()));

    let rows = execute(&plan, &snapshot, &params).await.expect("exec IC7");

    // Expect 3 distinct likers.
    assert_eq!(rows.len(), 3, "expected 3 likers, got {}", rows.len());
    let names: Vec<String> = rows
        .iter()
        .map(|r| match r.get("personFirstName") {
            Some(RuntimeValue::String(s)) => s.clone(),
            other => panic!("unexpected: {:?}", other),
        })
        .collect();
    // Ordered by likeCreationDate DESC, personId ASC.
    // Frank likes msg5 @ base+12d  ← most recent
    // Dave  likes msg2 @ base+11d  ← latest like by Dave (head of his
    //                                ordered list)
    // Eve   likes msg0 @ base+9d
    // Note: Dave actually likes msg0 *and* msg2 — both for Bob's msg5?
    // No — Dave's likes target msg0 (by Bob) and msg2 (by Dave himself).
    // Wait — IC7 filters via "creator = $personId", so only likes
    // pointing at Bob's messages count. Dave's like on msg2 (by Dave)
    // doesn't qualify.
    // So Dave only has a like on msg0 @ base+10d. Eve has a like on
    // msg0 @ base+9d. Frank has a like on msg5 @ base+12d.
    // Ordered by likeCreationDate DESC: Frank (12d), Dave (10d), Eve (9d).
    let _ = f;
    assert_eq!(names, vec!["Frank", "Dave", "Eve"]);
}

// ──────────────────────────────────────────────────────────────────────
// IC8 — Recent replies to a person's messages
// ──────────────────────────────────────────────────────────────────────

#[tokio::test]
async fn ic08_recent_replies() {
    let mut writer = WriterSession::open(store(), paths("ic08")).await.unwrap();
    let f = build_snb_micro_graph(&mut writer).await;
    let snapshot = writer.snapshot();

    let src = read_fixture("ic08_recent_replies.cypher");
    let q = parse(&src).expect("parse IC8");
    let plan = lower(&q).expect("lower IC8");

    let mut params = Params::new();
    // Bob authored msg0 and msg5. Replies to msg0: comment0 (Carol),
    // comment1 (Dave), comment3 (Frank). Replies to msg5: comment2 (Eve).
    // Total 4 replies; ordered by creationDate DESC, commentId ASC.
    params.insert("personId".into(), RuntimeValue::String(f.bob.to_string()));

    let rows = execute(&plan, &snapshot, &params).await.expect("exec IC8");

    assert_eq!(rows.len(), 4, "expected 4 replies, got {}", rows.len());
    let names: Vec<String> = rows
        .iter()
        .map(|r| match r.get("personFirstName") {
            Some(RuntimeValue::String(s)) => s.clone(),
            other => panic!("unexpected: {:?}", other),
        })
        .collect();
    // Order by creationDate DESC: comment3 (Frank, day 16), comment2 (Eve, 15),
    // comment1 (Dave, 14), comment0 (Carol, 13).
    let _ = f;
    assert_eq!(names, vec!["Frank", "Eve", "Dave", "Carol"]);
}

// ──────────────────────────────────────────────────────────────────────
// IC9 — Recent messages by friends-of-friends (variable-length *1..2)
// ──────────────────────────────────────────────────────────────────────

#[tokio::test]
async fn ic09_friends_of_friends_messages() {
    let mut writer = WriterSession::open(store(), paths("ic09")).await.unwrap();
    let f = build_snb_micro_graph(&mut writer).await;
    let snapshot = writer.snapshot();

    let src = read_fixture("ic09_friends_of_friends_messages.cypher");
    let q = parse(&src).expect("parse IC9");
    let plan = lower(&q).expect("lower IC9");

    let mut params = Params::new();
    params.insert("personId".into(), RuntimeValue::String(f.alice.to_string()));
    // maxDate slightly after the latest message to include all 8.
    let max_date = 1_700_000_000_000_i64 + 100 * 86_400_000;
    params.insert("maxDate".into(), RuntimeValue::Integer(max_date));

    let rows = execute(&plan, &snapshot, &params).await.expect("exec IC9");

    // Alice's KNOWS *1..2 friends (excluding Alice herself):
    //   1-hop: Bob, Carol  (alice→bob, alice→carol)
    //   2-hop: Dave (via bob→dave), Eve (via carol→eve)
    // Messages created by {Bob, Carol, Dave, Eve}: all 8 except those by
    // Frank (msg4). That gives 7 messages, but each is also reachable
    // through multiple hop counts (e.g. Bob is friend at *1 and *2 via
    // Bob→Dave→… wait, no — KNOWS *1..2 reaches him at hop 1 only).
    //
    // Care: the variable-length expand emits one row per hop that the
    // bound (min..max) admits. With *1..2 and bob reached at hop 1
    // (alice→bob), bob is matched once. dave is matched at hop 2 only
    // (alice→bob→dave). So each friend appears with the right multi-
    // plicity in the friend-list.
    //
    // BUT: friend appears in multiple paths. dave can be reached via
    // alice→bob→dave (hop 2). That's the only path of length ≤2.
    // bob can be reached at hop 1 (alice→bob). carol idem. eve via
    // carol→eve at hop 2. So each friend is matched once.
    //
    // Messages from these 4 friends: msg0 (bob), msg5 (bob), msg1 (carol),
    // msg6 (carol), msg2 (dave), msg3 (eve), msg7 (eve). Total 7 messages.
    assert!(
        !rows.is_empty(),
        "expected non-empty IC9 result, got 0 rows"
    );
    // Friends-of-friends produce the same friend node id only once per
    // hop path. Verify the result excludes msg4 (Frank's message).
    for row in &rows {
        match row.get("personId") {
            Some(RuntimeValue::String(s)) => {
                assert_ne!(
                    s,
                    &f.frank.to_string(),
                    "Frank should not appear as IC9 author"
                );
                assert_ne!(
                    s,
                    &f.alice.to_string(),
                    "Alice should be filtered by NOT friend._id = p._id"
                );
            }
            other => panic!("unexpected: {:?}", other),
        }
    }
    // Ordered DESC by creationDate then ASC by messageId — the first
    // row should be the latest qualifying message: msg7 (eve, day 7).
    match rows[0].get("messageId") {
        Some(RuntimeValue::String(s)) => {
            assert_eq!(s, &f.msg_ids[7].to_string());
        }
        other => panic!("unexpected: {:?}", other),
    }

    // Total row count: messages by {Bob, Carol, Dave, Eve} = 7. But
    // variable-length expand emits one row per (msg, hop-count) when
    // both *1 and *2 reach the same node. In this fixture each friend
    // is reachable via exactly one path within *1..2, so the count is
    // exactly 7 (we LIMIT 20 in the query so no truncation).
    assert_eq!(
        rows.len(),
        7,
        "expected 7 messages from FoF, got {} — rows: {:?}",
        rows.len(),
        rows.iter()
            .map(|r| r.get("personFirstName"))
            .collect::<Vec<_>>()
    );

    let _ = (f.bob, f.carol, f.dave, f.eve);
    let _ = f.msg_creators;
    let _ = f.comment_ids;
    let _ = f.comment_creators;
    let _ = f.comment_replies_to_msg;
}

// ──────────────────────────────────────────────────────────────────────
// IC1 — Friends with a given firstName (transitive *1..3)
// ──────────────────────────────────────────────────────────────────────

#[tokio::test]
async fn ic01_friends_by_name() {
    let mut writer = WriterSession::open(store(), paths("ic01")).await.unwrap();
    let f = build_snb_micro_graph(&mut writer).await;
    let snapshot = writer.snapshot();

    let src = read_fixture("ic01_friends_by_name.cypher");
    let q = parse(&src).expect("parse IC1");
    let plan = lower(&q).expect("lower IC1");

    let mut params = Params::new();
    params.insert("personId".into(), RuntimeValue::String(f.alice.to_string()));
    // Frank is at hop 3 from Alice (alice→bob→dave→frank or
    // alice→carol→eve→frank). Within *1..3 he is the only Person whose
    // firstName == "Frank".
    params.insert("firstName".into(), RuntimeValue::String("Frank".into()));

    let rows = execute(&plan, &snapshot, &params).await.expect("exec IC1");

    assert_eq!(rows.len(), 1, "expected exactly 1 friend, got {:?}", rows);
    match rows[0].get("firstName") {
        Some(RuntimeValue::String(s)) => assert_eq!(s, "Frank"),
        other => panic!("unexpected firstName: {:?}", other),
    }
    match rows[0].get("lastName") {
        Some(RuntimeValue::String(s)) => assert_eq!(s, "Foley"),
        other => panic!("unexpected lastName: {:?}", other),
    }
    match rows[0].get("friendId") {
        Some(RuntimeValue::String(s)) => assert_eq!(s, &f.frank.to_string()),
        other => panic!("unexpected friendId: {:?}", other),
    }
}

// ──────────────────────────────────────────────────────────────────────
// Smoke tests for the remaining LDBC IC queries (IC3-IC6, IC10-IC12).
//
// The micro graph doesn't have Country/City/Tag/Forum/Company nodes,
// so each query returns 0 rows. The point is to prove the entire
// parse → lower → optimize → execute pipeline accepts every IC*
// shape WITHOUT erroring. Correctness against a real LDBC-shaped
// dataset is validated by the bench harness (SF1/SF10 datasets).
// ──────────────────────────────────────────────────────────────────────

async fn execute_ic_smoke(name: &str, fixture: &str, person_param: NodeId) {
    let mut writer = WriterSession::open(store(), paths(name)).await.unwrap();
    build_snb_micro_graph(&mut writer).await;
    let snapshot = writer.snapshot();
    let src = read_fixture(fixture);
    let q = parse(&src).unwrap_or_else(|errs| panic!("parse {} failed: {:?}", name, errs));
    let plan = lower(&q).unwrap_or_else(|e| panic!("lower {} failed: {:?}", name, e));
    let mut params = Params::new();
    params.insert(
        "personId".into(),
        RuntimeValue::String(person_param.to_string()),
    );
    // Extra params used by various IC queries — supply sane values
    // regardless of which IC asks for them.
    params.insert("firstName".into(), RuntimeValue::String("Frank".into()));
    params.insert("countryAName".into(), RuntimeValue::String("AR".into()));
    params.insert("countryBName".into(), RuntimeValue::String("BR".into()));
    params.insert("tagName".into(), RuntimeValue::String("Music".into()));
    params.insert("tagClassName".into(), RuntimeValue::String("Person".into()));
    params.insert("countryName".into(), RuntimeValue::String("AR".into()));
    params.insert("workFromYear".into(), RuntimeValue::Integer(2020));
    params.insert("startDate".into(), RuntimeValue::Integer(0));
    params.insert("endDate".into(), RuntimeValue::Integer(2_000_000_000_000));
    params.insert("minDate".into(), RuntimeValue::Integer(0));
    let _rows = execute(&plan, &snapshot, &params)
        .await
        .unwrap_or_else(|e| panic!("execute {} failed: {:?}", name, e));
}

#[tokio::test]
async fn ic03_friends_in_two_countries_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic03", "ic03_friends_in_two_countries.cypher", person).await;
}

#[tokio::test]
async fn ic04_new_topics_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic04", "ic04_new_topics.cypher", person).await;
}

#[tokio::test]
async fn ic05_new_groups_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic05", "ic05_new_groups.cypher", person).await;
}

#[tokio::test]
async fn ic06_tag_cooccurrence_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic06", "ic06_tag_cooccurrence.cypher", person).await;
}

#[tokio::test]
async fn ic10_friend_recommendation_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic10", "ic10_friend_recommendation.cypher", person).await;
}

#[tokio::test]
async fn ic11_job_referral_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic11", "ic11_job_referral.cypher", person).await;
}

#[tokio::test]
async fn ic12_expert_search_smoke() {
    let person = NodeId::new();
    execute_ic_smoke("ic12", "ic12_expert_search.cypher", person).await;
}
